sfsu-csc-668-spring-2019/term-project-ourspace-team

backend/api/login.js, backend/app.js, client/package.json, client/src/components/Login_Components/LoginForm.js
app.js:
app.use() login route established
package.json: (client)
added proxy for communication through back end routers
api route folder:
-login.js
--app.get()
--app.post()
React Login Component:
-added 2 paragraph tags for demonstration purposes for get and post requests
-componentDidMount() uses get request for render of page
-clickedButton() uses post request which includes:
--example of json passing, example of state setting for response,
=> Working localhost post and get methods through React Login

backend/src/controllers/login.ts
Created the login controller that handles when a user ties to login whether the user exists and if it exists checks the hash in db with the users inputted password.
=> Created logic for the login controller

backend/src/controllers/login.ts
=> Reconfigured login.ts file into a more object orientated way similar

backend/src/app.ts, backend/src/controllers/registration.ts
i havent implemented jrob's suggestion 😮
=> Quick clean up of app.ts and registration

client/src/App.css, client/src/components/HomePage.js, client/src/components/Home_Components/PlacesList.js, client/src/components/LoggedInTopBar.js, client/src/components/Map_Components/Map.css, client/src/components/Map_Components/Map.js, client/src/components/TopBar.js, client/src/components/TrendingPage.js, client/src/components/Trending_Page_Components/TrendingPlacesList.js, client/src/routes.js
- Styled Map Component so that it takes up all available vertical space
- Added Trending Page
- Removed 'Messages' from Nav
- Connected Nav buttons to all pages
- Style tweaks for Home page
=> Tommy home page

client/public/index.html, client/src/components/HomePage.js, client/src/components/Map_Components/CommentsSection.js, client/src/components/Map_Components/Map.js, client/src/components/Map_Components/functions/createNewMap.js, client/src/components/Map_Components/functions/getContentString.js, client/src/components/Map_Components/functions/getMarker.js, client/src/components/Map_Components/functions/getPlacePhotos.js, client/src/components/Map_Components/functions/index.js, client/src/components/Map_Components/functions/loadGoogleMapsScript.js
Small updates to Map component
Added Material Style Bootstrap to index.html
Updated style of Marker InfoWindows
Updated style of Comments pages, working on allowing state to update Comments
=> Moved a lot of Map related functions out of the Map Component

client/src/App.css, client/src/App.js, client/src/components/Landing.js, client/src/components/LoginPage.js, client/src/components/Login_Components/LoginForm.css, client/src/components/Login_Components/LoginForm.js, client/src/components/Login_Components/RegisterForm.js, client/src/components/TopBar.js, client/src/routes.js
- Moved Login Module to separate page
- Restyled Landing Page
- Styling changes to Login and Register Components
- Added autofill Capabilities to forms
=> Tommy style changes

backend/src/app.ts, backend/src/controllers/homepage.ts, backend/src/controllers/login.ts, backend/src/controllers/maps.ts, backend/src/controllers/registration.ts, backend/src/entity/CommentEntity.ts, backend/src/entity/MapEntity.ts, backend/src/entity/PlaceEntity.ts, backend/src/entity/UserEntity.ts, backend/src/repository/map-repository.ts, backend/src/repository/user-repository.ts
Cleaning up some files.
Adding routes to be implemented.
Created and updated entities for maps, user, and places.
Controller and app.ts tags added.
Placeholder functions for map-repo.
=> Jarek place to map

backend/src/app.ts, backend/src/controllers/homepage.ts, backend/src/controllers/login.ts, backend/src/controllers/maps.ts, backend/src/controllers/registration.ts, backend/src/entity/CommentEntity.ts, backend/src/entity/MapEntity.ts, backend/src/entity/PlaceEntity.ts, backend/src/entity/UserEntity.ts, backend/src/repository/comment-repository.ts, backend/src/repository/map-repository.ts, backend/src/repository/place-repository.ts
Places can be added to maps given map id and place info.
Maps can be added to user through a route using auth user informaiton
Users have a map created on registration by default.
Maps tied to user
User tied to maps
Maps tied to places
Places tied to maps
=> Jarek add place

backend/src/app.ts, backend/src/controllers/follow.ts, backend/src/controllers/registration.ts, backend/src/entity/UserEntity.ts, backend/src/logic/followData.ts, backend/src/logic/followLogic.ts, backend/src/repository/user-repository.ts
-Created the follow system and now you can follow people
-Created a logic folder that does the logic for the controller (we might need a better name)
-Updated User repo so now it extends the standard repo
*Allows you to do user.save() rather than do userrepo.savefriend()
=> Follow system

backend/src/controllers/login.ts, backend/src/repository/user-repository.ts, client/src/actions/types.js, client/src/actions/userActions.js, client/src/components/Login_Components/LoginForm.js, client/src/reducers/index.js, client/src/reducers/userReducer.js
LoginForm can hit the login endpoint
If user data is returned, the data is saved to the Redux store.
If not, an error message is console logged.
=> Robert login redux

backend/src/controllers/maps.ts, backend/src/controllers/places.ts, client/package.json, client/src/App.js, client/src/actions/mapActions.js, client/src/config/store.js
The store is persistent even after app has been shut down
Will need to figure out how to purge state on logout
=> Implemented redux-persist

backend/src/app.ts, backend/src/controllers/comments.ts, backend/src/controllers/maps.ts, backend/src/controllers/places.ts, client/src/actions/mapActions.js
created an working example for getting the maps and the places from a mapid
=> Jarek returning maps

backend/src/app.ts, client/src/App.js, client/src/components/HomePage.js, client/src/components/Home_Components/PlacesList.js, client/src/components/Home_Components/ProfileCard.js, client/src/components/Landing.js, client/src/components/LoggedInTopBar.js, client/src/components/LoginPage.js, client/src/components/Login_Components/LoginForm.js, client/src/components/Login_Components/RegisterForm.js, client/src/components/ProfilePage.js, client/src/components/ProfilePage_Components/UserContent.js, client/src/components/SearchPage.js, client/src/components/SearchPage_Components/SearchPage.css, client/src/components/SearchPage_Components/SearchResults.js, client/src/components/TrendingPage.js, client/src/routes.js
- changed all 4 spaced/tabbed files to 2 spaced
- made style changes to user search component
- displaying gravatar images and username from state
- Login component redirects to the Home page on successful login
- pressing 'Enter' on login component will redirect to the Home Page on successful login
TODO: gravatar image and username are lost after page refresh
=> Tommy styling

backend/src/app.ts, backend/src/controllers/places.ts, backend/src/entity/MapEntity.ts, backend/src/repository/place-repository.ts, client/src/actions/mapActions.js, client/src/actions/types.js, client/src/components/Map_Components/Map.js, client/src/reducers/mapReducer.js
Map initial Position and Zoom now saved in Redux
Fixed back end code to add Places to DB
Front End buttons can add queries to add places, but they are not added to map yet
=> Map tabs updates

backend/src/app.ts, backend/src/controllers/maps.ts, backend/src/controllers/places.ts, backend/src/repository/map-repository.ts, client/src/actions/mapActions.js, client/src/actions/types.js, client/src/actions/userActions.js, client/src/components/Map_Components/Map.js, client/src/components/Map_Components/functions/getMarker.js, client/src/reducers/mapReducer.js, client/src/reducers/userReducer.js
Places can be saved in the front end, this updates the relations in the DB
On login an array of user related map ids are saved in Redux, the first id in that array is saved as openedMapId - this will be the initial map rendered when going to home page
On load of home page, we get the user's related maps for the openedMapId and render them to the map
If a user adds a place to the map the pin will render, but will not be re-rendered to a "saved place marker" until the user refreshes.
=> Render Markers

backend/src/app.ts, backend/src/controllers/login.ts, backend/src/controllers/maps.ts, backend/src/controllers/search.ts, backend/src/entity/MapEntity.ts, backend/src/repository/map-repository.ts, backend/src/repository/place-repository.ts, backend/src/repository/user-repository.ts
Big changes to querying data in user-repository. New column for map-entity that allows for type specification along with type changeability. New route to change the map type to a trending type.
=> Juan trending

client/src/components/Home_Components/PlacesList.js
- places list in the home page will display the user's saved places from state.
=> Tommy places list

backend/src/app.ts, backend/src/controllers/comments.ts, backend/src/controllers/follow.ts, backend/src/controllers/homepage.ts, backend/src/controllers/login.ts, backend/src/controllers/maps.ts, backend/src/controllers/places.ts, backend/src/controllers/registration.ts, backend/src/controllers/search.ts, backend/src/entity/MapEntity.ts, backend/src/entity/PlaceEntity.ts, backend/src/entity/UserEntity.ts, backend/src/repository/comment-repository.ts, backend/src/repository/map-repository.ts, backend/src/repository/place-repository.ts, backend/src/repository/user-repository.ts, backend/src/server.ts
Recommended Style Changes for submission.
=> Stylechanges

client/src/components/LoggedInTopBar.js, client/src/components/Login_Components/RegisterForm.js
- clicking the logout button will hit the /logout route and redirect the user to the index page
=> Connected to logout API
